[辻真吾・矢吹太朗『ゼロからはじめるデータサイエンス入門』（講談社, 2021）](https://github.com/taroyabuki/fromzero)

In [ ]:
# Google Colaboratoryの環境設定
if 'COLAB_GPU' in os.environ:
  !pip install h2o pandarallel pca pmdarima prophet | tail -n 1

In [ ]:
# これはPythonのコードの例です．
1 + 1
#> 2 # 注目すべき実行結果です．

# 1 コンピュータとネットワーク




## 1.1 コンピュータの基本操作




## 1.2 ネットワークの仕組み




# 2 データサイエンスのための環境




## 2.1 実行環境の選択




## 2.2 クラウド




## 2.3 Docker




## 2.4 ターミナルの使い方




## 2.5 RとPython




## 2.6 サンプルコードの利用

In [ ]:
1 + 1
# 2 # これは表示されない．

print(1 + 2)
# 3 # 表示される．

1 + 3
# 4 # 表示される．

# 3 RとPython




## 3.1 入門

In [ ]:
0x10
#> 16

In [ ]:
1.23e5
#> 123000.0

In [ ]:
2 * 3
#> 6

In [ ]:
10 / 3
#> 3.3333333333333335

In [ ]:
10 // 3 # 商
#> 3

10 % 3  # 余り
#> 1

In [ ]:
x = 2
y = 3
x * y
#> 6

x, y = 20, 30 # まとめて名付け
x * y
#> 600

In [ ]:
x = 1 + 1
# この段階では結果は表示されない

x # 変数名を評価する．
#> 2

In [ ]:
my_s = 'abcde'

In [ ]:
len(my_s)
#> 5

In [ ]:
'This is' ' a' ' pen.'
# あるいは
'This is ' + 'a' + ' pen.'
#> 'This is a pen.'

In [ ]:
my_s[1:4]
#> 'bcd'

In [ ]:
tmp = "{} is {}."
tmp.format('This', 'a pen')
#> 'This is a pen.'

In [ ]:
1 <= 2
#> True

1 < 0
#> False

In [ ]:
0.1 + 0.1 + 0.1 == 0.3
#> False

import math
math.isclose(0.1 + 0.1 + 0.1, 0.3)
#> True

In [ ]:
True and False # 論理積（かつ）
#> False

True or False  # 論理和（または）
#> True

not True       # 否定（でない）
#> False

In [ ]:
0 if 3 < 5 else 10
#> 0

In [ ]:
import os
os.getcwd()
#> '/home/jovyan/work'

In [ ]:
os.chdir('..')
os.getcwd()
#> '/home/jovyan'

## 3.2 関数

In [ ]:
import math
math.sqrt(4)
#> 2.0

In [ ]:
math.log(100, 10)
#> 2.0

In [ ]:
math.log(100)         # 自然対数
# あるいは
math.log(100, math.e) # 省略しない場合

#> 4.605170185988092

In [ ]:
math.log10(100) # 常用対数
#> 2.0

math.log2(1024) # 底が2の対数
#> 10.0

In [ ]:
def f(a, b):
    return a - b

In [ ]:
f(3, 5)
#> -2

In [ ]:
def f(a, b=5):
    return a - b

f(3) # f(3, 5)と同じこと
#> -2

In [ ]:
(lambda a, b: a - b)(3, 5)
#> -2

## 3.3 コレクション

In [ ]:
x = ['foo', 'bar', 'baz']

In [ ]:
len(x)
#> 3

In [ ]:
x[1]
#> 'bar'

In [ ]:
x[1] = 'BAR'
x # 結果の確認
#> ['foo', 'BAR', 'baz']

x[1] = 'bar' # 元に戻す．

In [ ]:
x[-2]
#> 'bar'

In [ ]:
x + ['qux']
#> ['foo', 'bar', 'baz', 'qux']

In [ ]:
x = x + ['qux']
# あるいは
#x.append('qux')

x # 結果の確認
#> ['foo', 'bar', 'baz', 'qux']

In [ ]:
list(range(5))
#> [0, 1, 2, 3, 4]

In [ ]:
list(range(0, 11, 2))
#> [0, 2, 4, 6, 8, 10]

In [ ]:
import numpy as np
np.arange(0, 1.1, 0.5)
#> array([0. , 0.5, 1. ])

In [ ]:
np.linspace(0, 100, 5)
#> array([ 0., 25., 50., 75., 100.])

In [ ]:
[10] * 5
#> [10, 10, 10, 10, 10]

In [ ]:
import numpy as np
x = np.array([2, 3, 5, 7])

x + 10 # 加算
#> array([12, 13, 15, 17])

x * 10 # 乗算
#> array([20, 30, 50, 70])

In [ ]:
x = [2, 3]
np.sin(x)
#> array([0.90929743, 0.14112001])

In [ ]:
x = np.array([2,  3,   5,    7])
y = np.array([1, 10, 100, 1000])
x + y
#> array([   3,   13,  105, 1007])

x * y
#> array([   2,   30,  500, 7000])

In [ ]:
np.dot(x, y)
# あるいは
x @ y

#> 7532

In [ ]:
x = np.array([True, False])
y = np.array([True, True])
x & y
#> array([ True, False])

In [ ]:
u = np.array([1, 2, 3])
v = np.array([1, 2, 3])
w = np.array([1, 2, 4])

all(u == v) # 全体の比較
#> True

all(u == w) # 全体の比較
#> False

u == v      # 要素ごとの比較
#> array([ True,  True,  True])

u == w      # 要素ごとの比較
#> array([ True,  True, False])

In [ ]:
(u == w).sum()  # 同じ要素の数
#> 2

(u == w).mean() # 同じ要素の割合
#> [1] 0.6666667

In [ ]:
x = [1, "two"]

In [ ]:
x[1]
#> 'two'

In [ ]:
x = {'apple' : 'りんご',
     'orange': 'みかん'}

In [ ]:
x['grape'] = 'ぶどう'

In [ ]:
x['apple']
# あるいは
tmp = 'apple'
x[tmp]

#> 'りんご'

In [ ]:
x = ['foo', 'bar', 'baz']
y = x
y[1] = 'BAR' # yを更新する．
y
#> ['foo', 'BAR', 'baz']

x            # xも変わる．
#> ['foo', 'BAR', 'baz']

In [ ]:
x = ['foo', 'bar', 'baz']
y = x.copy()             # 「y = x」とせずに，コピーする．
x == y, x is y
#> (True, False)         # xとyは，等価（内容は同じ）だが同一ではない．

y[1] = 'BAR'             # yを更新しても，
x
#> ['foo', 'bar', 'baz'] # xは変化しない．

## 3.4 データフレーム

In [ ]:
import pandas as pd

In [ ]:
my_df = pd.DataFrame({
    'name':    ['A', 'B', 'C', 'D'],
    'english': [ 60,  90,  70,  90],
    'math':    [ 70,  80,  90, 100],
    'gender':  ['f', 'm', 'm', 'f']})

In [ ]:
my_df = pd.DataFrame([
    ['A', 60,  70, 'f'],
    ['B', 90,  80, 'm'],
    ['C', 70,  90, 'm'],
    ['D', 90, 100, 'f']],
    columns=['name', 'english',
             'math', 'gender'])

In [ ]:
my_df.head()
# 結果は割愛

In [ ]:
r, c = my_df.shape # 行数と列数
r, c
#> (4, 4)

r # 行数（len(my_df)も可）
#> 4

c # 列数
#> 4

In [ ]:
from itertools import product
my_df2 = pd.DataFrame(
    product([1, 2, 3],
            [10, 100]),
    columns=['X', 'Y'])
my_df2
#>    X    Y
#> 0  1   10
#> 1  1  100
#> 2  2   10
#> 3  2  100
#> 4  3   10
#> 5  3  100

In [ ]:
my_df2.columns
#> Index(['X', 'Y'], dtype='object')

In [ ]:
my_df2.columns = ['P', 'Q']
my_df2
#>    P    Q
#> 0  1   10
#> 1  1  100
# 以下省略

In [ ]:
list(my_df.index)
#> [0, 1, 2, 3]

In [ ]:
my_df2.index = [
    'a', 'b', 'c', 'd', 'e', 'f']
my_df2
#>    P    Q
#> a  1   10
#> b  1  100
#> c  2   10
# 以下省略

In [ ]:
my_df3 = pd.DataFrame({
    'english': [ 60,  90,  70,  90],
    'math':    [ 70,  80,  90, 100],
    'gender':  ['f', 'm', 'm', 'f']},
    index=     ['A', 'B', 'C', 'D'])
my_df3
#>    english  math gender
#> A       60    70      f
#> B       90    80      m
#> C       70    90      m
#> D       90   100      f

In [ ]:
tmp = pd.DataFrame({
    'name'   : ['E'],
    'english': [80],
    'math'   : [80],
    'gender' : ['m']})
my_df2 = my_df.append(tmp)

In [ ]:
my_df2 = my_df.assign(id=[1, 2, 3, 4])

In [ ]:
my_df3 = my_df.copy()       # コピー
my_df3['id'] = [1, 2, 3, 4] # 更新
my_df3 # 結果の確認（割愛）

In [ ]:
my_df.iloc[0, 1]
#> 60

In [ ]:
x = my_df.iloc[:, 1]
# あるいは
x = my_df['english']
# あるいは
x = my_df.english
# あるいは
tmp = 'english'
x = my_df[tmp]

x # 結果の確認（割愛）

In [ ]:
x = my_df[['name', 'math']]
# あるいは
x = my_df.loc[:, ['name', 'math']]

In [ ]:
x = my_df.take([0, 2], axis=1)
# あるいは
x = my_df.iloc[:, [0, 2]]

In [ ]:
x = my_df.drop(
    columns=['english', 'gender'])
# あるいは
x = my_df.drop(
    columns=my_df.columns[[1, 3]])

In [ ]:
x = my_df.take([0, 2])
# あるいは
x = my_df.iloc[[0, 2], :]

In [ ]:
x = my_df.drop([1, 3])

In [ ]:
x = my_df[my_df['gender'] == 'm']
# あるいは
x = my_df.query('gender == "m"')

In [ ]:
x = my_df[(my_df['english'] > 80) & (my_df['gender'] == "m")]
# あるいは
x = my_df.query('english > 80 and gender == "m"')

In [ ]:
x = my_df[my_df['english'] == my_df['english'].max()]
# あるいは
tmp = my_df['english'].max()
x = my_df.query('english == @tmp')

In [ ]:
my_df2 = my_df.copy() # コピー
my_df2.loc[my_df['gender'] == 'm', 'gender'] = 'M'

In [ ]:
my_df2
#>   name  english  math gender
#> 0    A       60    70      f
#> 1    B       90    80      M
#> 2    C       70    90      M
#> 3    D       90   100      f

In [ ]:
x = my_df.sort_values('english')

In [ ]:
x = my_df.sort_values('english',
    ascending=False)

In [ ]:
import numpy as np
x = [2, 3, 5, 7, 11, 13, 17, 19, 23,
     29, 31, 37]
A = np.array(x).reshape(3, 4)
A
#> array([[ 2,  3,  5,  7],
#>        [11, 13, 17, 19],
#>        [23, 29, 31, 37]])

In [ ]:
A = my_df.iloc[:, [1, 2]].values
A
#> array([[ 60,  70],
#>        [ 90,  80],
#>        [ 70,  90],
#>        [ 90, 100]])

In [ ]:
pd.DataFrame(A)
#>     0    1
#> 0  60   70
#> 1  90   80
#> 2  70   90
#> 3  90  100

In [ ]:
A.T
#> array([[ 60,  90,  70,  90],
#>        [ 70,  80,  90, 100]])

In [ ]:
A.T @ A
#> array([[24700, 26700],
#>        [26700, 29400]])

In [ ]:
my_df = pd.DataFrame({
    'day': [25, 26, 27],
    'min': [20, 21, 15],
    'max': [24, 27, 21]})

In [ ]:
my_longer = my_df.melt(id_vars='day')
my_longer
#>    day variable  value
#> 0   25      min     20
#> 1   26      min     21
#> 2   27      min     15
#> 3   25      max     24
#> 4   26      max     27
#> 5   27      max     21

In [ ]:
my_wider = my_longer.pivot(
    index='day',
    columns='variable',
    values='value')
my_wider
#> variable  max  min
#> day
#> 25         24   20
#> 26         27   21
#> 27         21   15

In [ ]:
my_wider.plot(
    style='o-',
    xticks=my_wider.index, # x軸目盛り
    ylabel='temperature')  # y軸ラベル

## 3.5 1次元データの（非）類似度

In [ ]:
import numpy as np
from scipy.spatial import distance
from scipy.stats import pearsonr

A = np.array([3,   4,  5])
B = np.array([3,   4, 29])
C = np.array([9, -18,  8])

distance.euclidean(A, B)
#> 24.0

distance.euclidean(A, C)
#> 23.0

In [ ]:
distance.cityblock(A, B)
#> 24

distance.cityblock(A, C)
#> 31

In [ ]:
1 - distance.cosine(A, B)
#> 0.8169678632647616

1 - distance.cosine(A, C)
#> -0.032651157422416865

In [ ]:
1 - distance.correlation(A, B)
# あるいは
pearsonr(A, B)[0]
#> 0.8824975032927698

1 - distance.correlation(A, C)
# あるいは
pearsonr(A, C)[0]
#> -0.032662766723200676

In [ ]:
# 小数点以下は3桁表示
np.set_printoptions(precision=3)
import pandas as pd

my_df = pd.DataFrame({
    'x': [3,  3,   9],
    'y': [4,  4, -18],
    'z': [5, 29,   8]},
    index=['A', 'B', 'C'])

# ユークリッド距離
distance.cdist(my_df, my_df,
               metric='euclidean')
#> array([[ 0., 24., 23.],
#>        [24.,  0., 31.],
#>        [23., 31.,  0.]])

# マンハッタン距離
distance.cdist(my_df, my_df,
               metric='cityblock')
#> array([[ 0., 24., 31.],
#>        [24.,  0., 49.],
#>        [31., 49.,  0.]])

# コサイン類似度
1 - distance.cdist(my_df, my_df,
    metric='cosine')
#> array([[ 1.   ,  0.817, -0.033],
#>        [ 0.817,  1.   ,  0.293],
#>        [-0.033,  0.293,  1.   ]])

# 相関係数
1 - distance.cdist(my_df, my_df,
    metric='correlation')
#> array([[ 1.   ,  0.882, -0.033],
#>        [ 0.882,  1.   ,  0.441],
#>        [-0.033,  0.441,  1.   ]])

## 3.6 Rのパッケージ，Pythonのモジュール

In [ ]:
import math
import numpy as np
import pandas as pd

In [ ]:
import numpy
numpy.array([1, 2, 3, 4])

In [ ]:
import numpy as np
np.array([1, 2, 3, 4])

In [ ]:
from numpy import array
array([1, 2, 3, 4])

In [ ]:
from numpy import *
array([1, 2, 3, 4])

## 3.7 反復処理

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def f1(x):
    tmp = np.random.random(x)
    return np.mean(tmp)

f1(10)                # 動作確認
#> 0.5427033207230424 # 結果の例

In [ ]:
[f1(10) for i in range(3)]
#> [0.4864425069985622,
#>  0.4290935578857099,
#>  0.535206509631883]

In [ ]:
[f1(10)] * 3
#> [0.43725641184595576,
#>  0.43725641184595576,
#>  0.43725641184595576]

In [ ]:
v = [5, 10, 100]
[f1(x) for x in v] # 方法1
#> [0.454, 0.419, 0.552]

# あるいは

v = pd.Series([5, 10, 100])
v.apply(f1)        # 方法2
#> 0    0.394206
#> 1    0.503949
#> 2    0.532698
#> dtype: float64

In [ ]:
pd.Series([10] * 3).apply(f1)
# 結果は割愛

In [ ]:
def f2(n):
    tmp = np.random.random(n)
    return pd.Series([
        n,
        tmp.mean(),
        tmp.std(ddof=1)],
        index=['x', 'p', 'q'])

f2(10) # 動作確認
#> x    10.000000
#> p     0.405898 （平均の例）
#> q     0.317374 （標準偏差の例）
#> dtype: float64

In [ ]:
v = pd.Series([5, 10, 100])
v.apply(f2)
#>        x         p         q
#> 0    5.0  0.507798  0.207970
#> 1   10.0  0.687198  0.264427
#> 2  100.0  0.487872  0.280743

In [ ]:
def f3(x, y):
    tmp = np.random.random(x) * y
    return pd.Series([
        x,
        y,
        tmp.mean(),
        tmp.std(ddof=1)],
        index=['x', 'y', 'p', 'q'])

f3(10, 6) # 動作確認
#> x    10.000000
#> y     6.000000
#> p     2.136413 （平均の例）
#> q     1.798755 （標準偏差の例）
#> dtype: float64

In [ ]:
my_df = pd.DataFrame({
    'x': [5, 10, 100,  5, 10, 100],
    'y': [6,  6,   6, 12, 12,  12]})

my_df.apply(
  lambda row: f3(row['x'], row['y']),
  axis=1)
# あるいは
my_df.apply(lambda row:
            f3(*row), axis=1)

#>        x     y    p    q
#> 0   5.00  6.00 3.37 1.96
#> 1  10.00  6.00 1.92 0.95
#> 2 100.00  6.00 2.90 1.73
#> 3   5.00 12.00 6.82 3.00
#> 4  10.00 12.00 7.05 2.42
#> 5 100.00 12.00 5.90 3.54

In [ ]:
from pandarallel import pandarallel
pandarallel.initialize() # 準備

v = pd.Series([5, 10, 100])
v.parallel_apply(f1)
# 結果は割愛

## 3.8 その他

In [ ]:
x = 123
type(x)
#> int

In [ ]:
%whos
#> Variable   Type      Data/Info
#> ------------------------------
#> x          int       123

In [ ]:
import math
?math.log
# あるいは
help(math.log)

In [ ]:
import numpy as np
v = [1, np.nan, 3]
v
#> [1, nan, 3]

In [ ]:
np.isnan(v[1])
#> True

v[1] == np.nan # 誤り
#> False

# 4 統計入門




## 4.1 記述統計

In [ ]:
import numpy as np
import pandas as pd

x = [165, 170, 175, 180, 185]
np.mean(x) # リストの場合
#> 175.0

x = np.array( # アレイ
    [165, 170, 175, 180, 185])
x.mean() # np.mean(x)も可
#> 175.0

x = pd.Series( # シリーズ
    [165, 170, 175, 180, 185])
x.mean() # np.mean(x)も可
#> 175.0

In [ ]:
n = len(x) # サンプルサイズ
sum(x) / n
#> 175.0

In [ ]:
y = [173, 174, 175, 176, 177]
np.mean(y)
#> 175.0

In [ ]:
np.var(x, ddof=1) # xの分散
#> 62.5

np.var(y, ddof=1) # yの分散
#> 2.5

In [ ]:
sum((x - np.mean(x))**2) / (n - 1)
#> 62.5

In [ ]:
np.std(x, ddof=1) # xの標準偏差
#> 7.905694150420948

np.std(y, ddof=1) # yの標準偏差
#> 1.5811388300841898

In [ ]:
np.var(x, ddof=1)**0.5 # xの標準偏差
#> 7.905694150420948

In [ ]:
s = pd.Series(x)
s.describe()
#> count      5.000000 （データ数）
#> mean     175.000000 （平均）
#> std        7.905694 （標準偏差）
#> min      165.000000 （最小値）
#> 25%      170.000000 （第1四分位数）
#> 50%      175.000000 （中央値）
#> 75%      180.000000 （第3四分位数）
#> max      185.000000 （最大値）
#> dtype: float64

In [ ]:
# s.describe()で計算済み

In [ ]:
x = [165, 170, 175, 180, 185]

np.var(x, ddof=1) # 不偏分散
#> 62.5

np.var(x, ddof=0) # 標本分散
#> 50.0

In [ ]:
np.std(x, ddof=1) # √不偏分散
#> 7.905694150420949

np.std(x, ddof=0) # √標本分散
#> 7.0710678118654755

In [ ]:
np.std(x, ddof=1) / len(x)**0.5
#> 3.5355339059327373

In [ ]:
import numpy as np
import pandas as pd

my_df = pd.DataFrame({
    'name':    ['A', 'B', 'C', 'D'],
    'english': [ 60,  90,  70,  90],
    'math':    [ 70,  80,  90, 100],
    'gender':  ['f', 'm', 'm', 'f']})

In [ ]:
my_df['english'].var(ddof=1)
# あるいは
np.var(my_df['english'], ddof=1)

#> 225.0

In [ ]:
my_df.var()
# あるいは
my_df.apply('var')
# あるいは
my_df.iloc[:, [1, 2]].apply(
    lambda x: np.var(x, ddof=1))

#> english    225.000000
#> math       166.666667
#> dtype: float64

In [ ]:
my_df.describe()
#>        english        math
#> count      4.0    4.000000
#> mean      77.5   85.000000
#> std       15.0   12.909944
#> min       60.0   70.000000
#> 25%       67.5   77.500000
#> 50%       80.0   85.000000
#> 75%       90.0   92.500000
#> max       90.0  100.000000

In [ ]:
from collections import Counter
Counter(my_df.gender)
#> Counter({'f': 2, 'm': 2})

# あるいは

my_df.groupby('gender').apply(len)
#> gender
#> f    2
#> m    2
#> dtype: int64

In [ ]:
my_df2 = my_df.assign(
    excel=my_df.math >= 80)
pd.crosstab(my_df2.gender,
            my_df2.excel)
#> excel   False  True
#> gender
#> f           1      1
#> m           0      2

In [ ]:
my_df.groupby('gender').mean()
# あるいは
my_df.groupby('gender').agg('mean')
# あるいは
my_df.groupby('gender').agg(np.mean)

#>         english  math
#> gender
#> f          75.0  85.0
#> m          80.0  85.0

## 4.2 データの可視化

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
iris = sm.datasets.get_rdataset('iris', 'datasets').data
iris.head()
#>    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
#> 0           5.1          3.5           1.4          0.2  setosa
#> 1           4.9          3.0           1.4          0.2  setosa
#> 2           4.7          3.2           1.3          0.2  setosa
#> 3           4.6          3.1           1.5          0.2  setosa
#> 4           5.0          3.6           1.4          0.2  setosa

In [ ]:
iris.hist('Sepal.Length')

In [ ]:
my_df = pd.DataFrame(
    {'x': [10, 20, 30]})
my_df.hist('x', bins=2) # 階級数は2

In [ ]:
x = iris['Sepal.Length']
tmp = np.linspace(min(x), max(x), 10)
iris.hist('Sepal.Length',
          bins=tmp.round(2))

In [ ]:
iris.plot('Sepal.Length',
          'Sepal.Width',
          kind='scatter')

In [ ]:
iris.boxplot()

In [ ]:
pd.options.display.float_format = (
    '{:.2f}'.format)
my_df = (iris.describe().transpose()
    [['mean', 'std']])
my_df['se'] = (my_df['std'] /
               len(iris)**0.5)
my_df
#>               mean  std   se
#> Sepal.Length  5.84 0.83 0.07
#> Sepal.Width   3.06 0.44 0.04
#> Petal.Length  3.76 1.77 0.14
#> Petal.Width   1.20 0.76 0.06

In [ ]:
my_df.plot(y='mean', kind='bar', yerr='se', capsize=10)

In [ ]:
my_group = iris.groupby('Species')                    # 品種ごとに，
my_df = my_group.agg('mean')                          # 各変数の，平均と
my_se = my_group.agg(lambda x: x.std() / len(x)**0.5) # 標準誤差を求める．
my_se
#>             Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
#> Species
#> setosa              0.05         0.05          0.02         0.01
#> versicolor          0.07         0.04          0.07         0.03
#> virginica           0.09         0.05          0.08         0.04

In [ ]:
my_group.agg('mean').plot(kind='bar', yerr=my_se, capsize=5)

In [ ]:
from statsmodels.graphics.mosaicplot \
    import mosaic

my_df = pd.DataFrame({
    'Species': iris.Species,
    'w_Sepal': iris['Sepal.Width'] > 3})

my_table = pd.crosstab( # 分割表
    my_df['Species'],
    my_df['w_Sepal'])
my_table
#> w_Sepal     False  True
#> Species
#> setosa          8     42
#> versicolor     42      8
#> virginica      33     17

mosaic(my_df,
       index=['Species', 'w_Sepal'])

In [ ]:
my_table.columns = [str(x) for x in my_table.columns]
my_table.index   = [str(x) for x in my_table.index]
mosaic(my_df, index=['Species', 'w_Sepal'], labelizer=lambda k: my_table.loc[k])

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2, 2, 100)
y = x**3 - x
plt.plot(x, y)

## 4.3 乱数

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
rng = np.random.default_rng()

In [ ]:
x = np.random.choice(
    a=range(1, 7), # 1から6
    size=10000,    # 乱数の数
    replace=True)  # 重複あり
# あるいは
x = np.random.randint(
# あるいは
#x = rng.integers(
    low=1,      # 最小
    high=7,     # 最大+1
    size=10000) # 乱数の数

plt.hist(x, bins=6) # ヒストグラム

In [ ]:
x = np.random.random(size=1000)
# あるいは
x = rng.random(size=10000)
# あるいは
x = np.random.uniform(
    low=0,     # 最小
    high=1,    # 最大
    size=1000) # 乱数の数
plt.hist(x)

In [ ]:
tmp = np.random.uniform(
    low=1,     # 最小
    high=7,    # 最大 + 1
    size=1000) # 乱数の数
x = [int(k) for k in tmp]
plt.hist(x, bins=6) # 結果は割愛

In [ ]:
n = 100
p = 0.5
r = 10000
x = np.random.binomial(
# あるいは
#x = rng.binomial(
    n=n,    # 試行回数
    p=p,    # 確率
    size=r) # 乱数の数
plt.hist(x, bins=max(x) - min(x))

In [ ]:
r = 10000
x = np.random.normal(
# あるいは
#x = rng.normal(
    loc=50,  # 平均
    scale=5, # 標準偏差
    size=r)  # 乱数の数
plt.hist(x, bins=40)

In [ ]:
import numpy as np
import pandas as pd

def f(k):
    n = 10000
    tmp = [g(np.random.normal(size=k, scale=3)) for _ in range(n)]
    return pd.Series([k,
                      np.mean(tmp),                  # 平均
                      np.std(tmp, ddof=1) / n**0.5], # 標準誤差
                     index=['k', 'mean', 'se'])

In [ ]:
def g(x):
    return np.var(x, ddof=1)
pd.Series([10, 20, 30]).apply(f)
#>       k      mean        se
#> 0  10.0  9.025140  0.042690
#> 1  20.0  9.022280  0.029525
#> 2  30.0  8.983166  0.023584

In [ ]:
def g(x):
    return np.std(x, ddof=1)
pd.Series([10, 20, 30]).apply(f)
#>       k      mean        se
#> 0  10.0  2.923114  0.006983
#> 1  20.0  2.961450  0.004811
#> 2  30.0  2.968328  0.003977

In [ ]:
from math import gamma

def g(x):
    n = len(x)
    return (np.std(x, ddof=1) *
            (np.sqrt((n - 1) / 2) *
             gamma((n - 1) / 2) /
             gamma(n / 2)))
pd.Series([10, 20, 30]).apply(f)
#>       k      mean        se
#> 0  10.0  3.005788  0.007121
#> 1  20.0  3.001857  0.004894
#> 2  30.0  2.995965  0.003925

## 4.4 統計的推測

In [ ]:
from statsmodels.stats.proportion import binom_test, proportion_confint

binom_test(count=2,                 # 当たった回数
           nobs=15,                 # くじを引いた回数
           prop=4 / 10,             # 当たる確率（仮説）
           alternative='two-sided') # 両側検定（デフォルト）
                                    # 左片側検定なら'smaller'
                                    # 右片側検定なら'larger'
#> 0.03646166155263999

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats

t = 4 / 10                        # 当たる確率
n = 15                            # くじを引いた回数
x = np.array(range(0, n + 1))     # 当たった回数
my_pr  = stats.binom.pmf(x, n, t) # x回当たる確率
my_pr2 = stats.binom.pmf(2, n, t) # 2回当たる確率

my_data = pd.DataFrame({'x': x, 'y1': my_pr, 'y2': my_pr})
my_data.loc[my_pr >  my_pr2, 'y1'] = np.nan # 当たる確率が，2回当たる確率超過
my_data.loc[my_pr <= my_pr2, 'y2'] = np.nan # 当たる確率が，2回当たる確率以下
ax = my_data.plot(x='x', style='o', ylabel='probability',
                  legend=False)         # 凡例を表示しない．
ax.hlines(y=my_pr2, xmin=0, xmax=15)    # 水平線
ax.vlines(x=x,      ymin=0, ymax=my_pr) # 垂直線

In [ ]:
a = 0.05
proportion_confint(
    count=2, # 当たった回数
    nobs=15, # くじを引いた回数
    alpha=a, # 有意水準（省略可）
    method='binom_test')
#> (0.024225732468536626,
#>  0.3967139842509865)

In [ ]:
a = 0.05 # 有意水準
tmp = np.linspace(0, 1, 100)

my_df = pd.DataFrame({
    't': tmp,                                                  # 当たる確率
    'q': a,                                                    # 水平線
    'p': [binom_test(count=2, nobs=15, prop=t) for t in tmp]}) # p値

my_df.plot(x='t', legend=None, xlabel=r'$\theta$', ylabel=r'p-value')

In [ ]:
from statsmodels.stats.weightstats import CompareMeans, DescrStatsW

X = [32.1, 26.2, 27.5, 31.8, 32.1, 31.2, 30.1, 32.4, 32.3, 29.9,
     29.6, 26.6, 31.2, 30.9, 29.3]
Y = [35.4, 34.6, 31.1, 32.4, 33.3, 34.7, 35.3, 34.3, 32.1, 28.3,
     33.3, 30.5, 32.6, 33.3, 32.2]

a = 0.05          # 有意水準（デフォルト） = 1 - 信頼係数
alt = 'two-sided' # 両側検定（デフォルト）
                  # 左片側検定なら'smaller'
                  # 右片側検定なら'larger'

d = DescrStatsW(np.array(X) - np.array(Y)) # 対標本の場合
d.ttest_mean(alternative=alt)[1]           # p値
#> 0.0006415571512322235

d.tconfint_mean(alpha=a, alternative=alt) # 信頼区間
#> (-3.9955246743198867, -1.3644753256801117)

In [ ]:
c = CompareMeans(DescrStatsW(X), DescrStatsW(Y)) # 対標本でない場合

ve = 'pooled' # 等分散を仮定する（デフォルト）．仮定しないなら'unequal'．
c.ttest_ind(alternative=alt, usevar=ve)[1] # p値
#> 0.000978530937238609

c.tconfint_diff(alpha=a, alternative=alt, usevar=ve) # 信頼区間
#> (-4.170905570517185, -1.1890944294828283)

In [ ]:
import pandas as pd
my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/smoker.csv')
my_data = pd.read_csv(my_url)

In [ ]:
my_data.head()
#>   alive smoker
#> 0   Yes     No
#> 1   Yes     No
#> 2   Yes     No
#> 3   Yes     No
#> 4   Yes     No

In [ ]:
my_table = pd.crosstab(
    my_data['alive'],
    my_data['smoker'])
my_table
#> smoker   No  Yes
#> alive
#> No      117   54
#> Yes     950  348

In [ ]:
from scipy.stats import chi2_contingency
chi2_contingency(my_table, correction=False)[1]
#> 0.18860725715300422

In [ ]:
X = [0] * 13 + [1] * 2 # 手順1
X
#> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]

tmp = np.random.choice(X, 15, replace=True) # 手順2
tmp
#> array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0])

sum(tmp) # 手順3
#> 2

n = 10**5
result = [sum(np.random.choice(X, len(X), replace=True)) for _ in range(n)] # 手順4

In [ ]:
import matplotlib.pyplot as plt
plt.hist(result, bins=range(0, 16))

In [ ]:
np.quantile(result, [0.025, 0.975])
#> array([0., 5.])

# 5 前処理




## 5.1 データの読み込み

In [ ]:
!wget https://raw.githubusercontent.com/taroyabuki/fromzero/master/data/exam.csv

In [ ]:
import pandas as pd
my_df = pd.read_csv('exam.csv')
my_df
#>   name  english  math gender
#> 0    A       60    70      f
#> 1    B       90    80      m
#> 2    C       70    90      m
#> 3    D       90   100      f

In [ ]:
my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/exam.csv')
my_df = pd.read_csv(my_url)

In [ ]:
my_df2 = pd.read_csv('exam.csv',
    index_col='name')
my_df2
#>       english  math gender
#> name
#> A          60    70      f
#> B          90    80      m
#> C          70    90      m
#> D          90   100      f

In [ ]:
my_df.to_csv('exam2.csv', index=False)

In [ ]:
my_df2.to_csv('exam3.csv')

In [ ]:
my_df = pd.read_csv('exam.csv',
    encoding='UTF-8')

In [ ]:
my_df.to_csv('exam2.csv', index=False, encoding='UTF-8')

In [ ]:
my_url = 'https://taroyabuki.github.io/fromzero/exam.html'
my_tables = pd.read_html(my_url)

In [ ]:
my_tables
#> [   Unnamed: 0 name  english ...
#>  0         NaN    A       60 ...
#>  1         NaN    B       90 ...
#>  2         NaN    C       70 ...
#>  3         NaN    D       90 ...]

In [ ]:
my_tables[0]
#>    Unnamed: 0 name  english ...
#> 0         NaN    A       60 ...
#> 1         NaN    B       90 ...
#> 2         NaN    C       70 ...
#> 3         NaN    D       90 ...

In [ ]:
# 1列目以降を取り出す．
my_data = my_tables[0].iloc[:, 1:]
my_data
#>   name  english  math gender
#> 0    A       60    70      f
#> 1    B       90    80      m
#> 2    C       70    90      m
#> 3    D       90   100      f

In [ ]:
my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/exam.json')
my_data = pd.read_json(my_url)
#my_data = pd.read_json('exam.json') # （ファイルを使う場合）
my_data
#>   name  english  math gender
#> 0    A       60    70      f
#> 1    B       90    80      m
#> 2    C       70    90      m
#> 3    D       90   100      f

In [ ]:
import xml.etree.ElementTree as ET
from urllib.request import urlopen

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/exam.xml')
with urlopen(my_url) as f:
    my_tree = ET.parse(f)       # XMLデータの読み込み

#my_tree = ET.parse('exam.xml') # （ファイルを使う場合）
my_ns = '{https://www.example.net/ns/1.0}' # 名前空間

In [ ]:
my_records = my_tree.findall(f'.//{my_ns}record')

In [ ]:
def f(record):
    my_dic1 = record.attrib # 属性を取り出す．
    # 子要素の名前と内容のペアを辞書にする．
    my_dic2 = {child.tag.replace(my_ns, ''): child.text for child in list(record)}
    return {**my_dic1, **my_dic2} # 辞書を結合する．

In [ ]:
my_data = pd.DataFrame([f(record) for record in my_records])
my_data['english'] = pd.to_numeric(my_data['english'])
my_data['math']    = pd.to_numeric(my_data['math'])
my_data
#>    english  math gender name
#> 0       60    70      f    A
#> 1       90    80      m    B
#> 2       70    90      m    C
#> 3       90   100      f    D

## 5.2 データの変換

In [ ]:
import numpy as np
from scipy.stats import zscore

x1 = [1, 2, 3]

z1 = ((x1 - np.mean(x1)) /
      np.std(x1, ddof=1))
# あるいは
z1 = zscore(x1, ddof=1)

z1
#> array([-1.,  0.,  1.])

In [ ]:
z1.mean(), np.std(z1, ddof=1)
#> (0.0, 1.0)

In [ ]:
z1 * np.std(x1, ddof=1) + np.mean(x1)
#> array([1., 2., 3.])

In [ ]:
x2 = [1, 3, 5]
z2 = ((x2 - np.mean(x1)) /
      np.std(x1, ddof=1))
z2.mean(), np.std(z2, ddof=1)
#> (1.0, 2.0)

In [ ]:
import pandas as pd
from sklearn.preprocessing import (
    OneHotEncoder)

my_df = pd.DataFrame({
    'id':    [ 1 ,  2 ,  3 ],
    'class': ['A', 'B', 'C']})

my_enc = OneHotEncoder()
tmp = my_enc.fit_transform(
    my_df[['class']]).toarray()
my_names = my_enc.get_feature_names() \
if hasattr(my_enc, 'get_feature_names') \
else my_enc.get_feature_names_out()
pd.DataFrame(tmp, columns=my_names)
#>    x0_A  x0_B  x0_C
#> 0   1.0   0.0   0.0
#> 1   0.0   1.0   0.0
#> 2   0.0   0.0   1.0

In [ ]:
my_df2 = pd.DataFrame({
    'id':    [ 4 ,  5,   6 ],
    'class': ['B', 'C', 'B']})
tmp = my_enc.transform(
    my_df2[['class']]).toarray()
pd.DataFrame(tmp, columns=my_names)
#>    x0_A  x0_B  x0_C
#> 0   0.0   1.0   0.0
#> 1   0.0   0.0   1.0
#> 2   0.0   1.0   0.0

In [ ]:
my_enc = OneHotEncoder(drop='first')

tmp = my_enc.fit_transform(
    my_df[['class']]).toarray()
my_names = my_enc.get_feature_names() \
if hasattr(my_enc, 'get_feature_names') \
else my_enc.get_feature_names_out()
pd.DataFrame(tmp, columns=my_names)
#>    x0_B  x0_C
#> 0   0.0   0.0
#> 1   1.0   0.0
#> 2   0.0   1.0

tmp = my_enc.transform(
    my_df2[['class']]).toarray()
pd.DataFrame(tmp, columns=my_names)
#>    x0_B  x0_C
#> 0   1.0   0.0
#> 1   0.0   1.0
#> 2   1.0   0.0

# 6 機械学習の目的・データ・手法




## 6.1 機械学習の目的（本書の場合）




## 6.2 機械学習のためのデータ

In [ ]:
import statsmodels.api as sm
iris = sm.datasets.get_rdataset('iris', 'datasets').data
iris.head()
#>    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
#> 0           5.1          3.5           1.4          0.2  setosa
# 以下省略

In [ ]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head()
#>    sepal_length  sepal_width  petal_length  petal_width species
#> 0           5.1          3.5           1.4          0.2  setosa
# 以下省略

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
tmp = load_iris()
iris = pd.DataFrame(tmp.data, columns=tmp.feature_names)
iris['target'] = tmp.target_names[tmp.target]
iris.head()
#>    sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
#> 0                5.1               3.5  ...               0.2  setosa
# 以下省略

## 6.3 機械学習のための手法




# 7 回帰1（単回帰）




## 7.1 自動車の停止距離




## 7.2 データの確認

In [ ]:
import statsmodels.api as sm
my_data = sm.datasets.get_rdataset('cars', 'datasets').data

In [ ]:
my_data.shape
#> (50, 2)

In [ ]:
my_data.head()
#>    speed  dist
#> 0      4     2
#> 1      4    10
#> 2      7     4
#> 3      7    22
#> 4      8    16

In [ ]:
my_data.describe()
#>            speed        dist
#> count  50.000000   50.000000
#> mean   15.400000   42.980000
#> std     5.287644   25.769377
#> min     4.000000    2.000000
#> 25%    12.000000   26.000000
#> 50%    15.000000   36.000000
#> 75%    19.000000   56.000000
#> max    25.000000  120.000000

In [ ]:
my_data.plot(x='speed', style='o')

## 7.3 回帰分析

In [ ]:
import seaborn as sns
import statsmodels.api as sm

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
ax = sns.regplot(x='speed', y='dist', data=my_data)
ax.vlines(x=21.5, ymin=-5, ymax=67,   linestyles='dotted')
ax.hlines(y=67,   xmin=4,  xmax=21.5, linestyles='dotted')
ax.set_xlim(4, 25)
ax.set_ylim(-5, 125)

In [ ]:
import statsmodels.api as sm
my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

In [ ]:
# モデルの指定
from sklearn.linear_model import LinearRegression
my_model = LinearRegression()

# 訓練（モデルをデータにフィットさせる．）
my_model.fit(X, y)

# まとめて実行してもよい．
# my_model = LinearRegression().fit(X, y)

In [ ]:
my_model.intercept_, my_model.coef_
#> (-17.579094890510973,
#>  array([3.93240876]))

In [ ]:
tmp = [[21.5]]
my_model.predict(tmp)
#> array([66.96769343])

In [ ]:
import numpy as np
import pandas as pd

tmp = pd.DataFrame({'speed': np.linspace(min(my_data.speed),
                                         max(my_data.speed),
                                         100)})
tmp['model'] = my_model.predict(tmp)

In [ ]:
pd.concat([my_data, tmp]).plot(
    x='speed', style=['o', '-'])

## 7.4 当てはまりの良さの指標

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

my_model = LinearRegression()
my_model.fit(X, y)
y_ = my_model.predict(X)
my_data['y_'] = y_

In [ ]:
pd.options.display.float_format = (
    '{:.2f}'.format)
my_data['residual'] = y - y_
my_data.head()
#>    speed  dist    y_  residual
#> 0      4     2 -1.85      3.85
#> 1      4    10 -1.85     11.85
#> 2      7     4  9.95     -5.95
#> 3      7    22  9.95     12.05
#> 4      8    16 13.88      2.12

In [ ]:
ax = my_data.plot(x='speed', y='dist', style='o', legend=False)
my_data.plot(x='speed', y='y_', style='-', legend=False, ax=ax)
ax.vlines(x=X, ymin=y, ymax=y_, linestyles='dotted')

In [ ]:
mean_squared_error(y, y_)**0.5
# あるいは
(my_data['residual']**2).mean()**0.5

#> 15.068855995791381

In [ ]:
my_model.score(X, y)
# あるいは
r2_score(y_true=y, y_pred=y_)
#> 0.6510793807582509

In [ ]:
import numpy as np
np.corrcoef(y, y_)[0, 1]**2
#> 0.6510793807582511

In [ ]:
my_test = my_data[:3]
X = my_test[['speed']]
y = my_test['dist']
y_ = my_model.predict(X)

my_model.score(X, y)
# あるいは
r2_score(y_true=y, y_pred=y_)
#> -4.498191310376778 # 決定係数1

np.corrcoef(y, y_)[0, 1]**2
#> 0.0769230769230769 # 決定係数6

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

my_data = sm.datasets.get_rdataset('cars', 'datasets').data

my_idx = [1, 10, 26, 33, 38, 43]
my_sample = my_data.iloc[my_idx, ]
X, y = my_sample[['speed']], my_sample['dist']

In [ ]:
d = 5
X5 = PolynomialFeatures(d, include_bias=False).fit_transform(X) # Xの1乗から5乗の変数

my_model = LinearRegression()
my_model.fit(X5, y)
y_ = my_model.predict(X5)

In [ ]:
((y - y_)**2).mean()**0.5
#> 7.725744805546204e-07 # RMSE

my_model.score(X5, y)
#> 0.9999999999999989 # 決定係数1

np.corrcoef(y, y_)[0, 1]**2
#> 0.9999999999999991 # 決定係数6

In [ ]:
tmp = pd.DataFrame({'speed': np.linspace(min(my_data.speed),
                                         max(my_data.speed),
                                         100)})
X5 = PolynomialFeatures(d, include_bias=False).fit_transform(tmp)
tmp['model'] = my_model.predict(X5)

my_sample = my_sample.assign(sample=y)
my_df = pd.concat([my_data, my_sample, tmp])
my_df.plot(x='speed', style=['o', 'o', '-'], ylim=(0, 130))

## 7.5 K最近傍法

In [ ]:
# 準備
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

# 訓練
my_model = KNeighborsRegressor()
my_model.fit(X, y)

# 可視化の準備
tmp = pd.DataFrame({'speed': np.linspace(min(my_data.speed),
                                         max(my_data.speed),
                                         100)})
tmp['model'] = my_model.predict(tmp)

In [ ]:
pd.concat([my_data, tmp]).plot(
    x='speed', style=['o', '-'])

In [ ]:
y_ = my_model.predict(X)

((y - y_)**2).mean()**0.5
#> 13.087184571174962 # RMSE

my_model.score(X, y)
#> 0.7368165812204317 # 決定係数1

np.corrcoef(y, y_)[0, 1]**2
#> 0.7380949412509705 # 決定係数6

## 7.6 検証

In [ ]:
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# データの準備
my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

# モデルの指定
my_model = LinearRegression()

# 検証（5分割交差検証）
my_scores = cross_val_score(my_model, X, y)

# 5個の決定係数1を得る．
my_scores
#> array([-0.25789256, -0.21421069, -0.30902773, -0.27346232,  0.02312918])

# 平均を決定係数1（検証）とする．
my_scores.mean()
#> -0.20629282165364665

In [ ]:
my_scores = cross_val_score(my_model, X, y,
                            scoring='neg_root_mean_squared_error')
-my_scores.mean()
#> 15.58402474583013 # RMSE（検証）

In [ ]:
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score, LeaveOneOut

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']
my_model = LinearRegression().fit(X, y)
y_ = my_model.predict(X)

In [ ]:
# RMSE（訓練）
mean_squared_error(y, y_)**0.5
#> 15.068855995791381

# 決定係数1（訓練）
my_model.score(X, y)
# あるいは
r2_score(y_true=y, y_pred=y_)
#> 0.6510793807582509

# 決定係数6（訓練）
np.corrcoef(y, y_)[0, 1]**2
#> 0.6510793807582511

In [ ]:
my_scores = cross_val_score(my_model, X, y,
                            scoring='neg_root_mean_squared_error')
-my_scores.mean()
#> 15.301860331378464  # RMSE（検証）

my_scores = cross_val_score(my_model, X, y, scoring='r2') # scoring='r2'は省略可
my_scores.mean()
#> 0.49061365458235245 # 決定係数1（検証）

In [ ]:
# 方法1
my_scores1 = cross_val_score(my_model, X, y, cv=LeaveOneOut(),
                             scoring='neg_mean_squared_error')
(-my_scores1.mean())**0.5
#> 15.697306009399101

# 方法2
my_scores2 = cross_val_score(my_model, X, y, cv=LeaveOneOut(),
                             scoring='neg_root_mean_squared_error')
(my_scores2**2).mean()**0.5
#> 15.697306009399101

In [ ]:
-my_scores2.mean()
#> 12.059178648637483

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

my_lm_scores = cross_val_score(
    LinearRegression(),
    X, y, cv=LeaveOneOut(), scoring='neg_mean_squared_error')

my_knn_socres = cross_val_score(
    KNeighborsRegressor(n_neighbors=5),
    X, y, cv=LeaveOneOut(), scoring='neg_mean_squared_error')

In [ ]:
(-my_lm_scores.mean())**0.5
#> 15.697306009399101 # 線形回帰分析

(-my_knn_socres.mean())**0.5
#> 16.07308308943869 # K最近傍法

In [ ]:
my_df = pd.DataFrame({
    'lm': -my_lm_scores,
    'knn': -my_knn_socres})
my_df.head()
#>            lm     knn
#> 0   18.913720  108.16
#> 1  179.215044    0.64
#> 2   41.034336   64.00
#> 3  168.490212  184.96
#> 4    5.085308    0.00

In [ ]:
my_df.boxplot().set_ylabel("$r^2$")

In [ ]:
from statsmodels.stats.weightstats import DescrStatsW
d = DescrStatsW(my_df.lm - my_df.knn)
d.ttest_mean()[1] # p値
#> 0.6952755720536115

d.tconfint_mean(alpha=0.05, alternative='two-sided') # 信頼区間
#> (-72.8275283312228, 48.95036023665703)

## 7.7 パラメータチューニング

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV, LeaveOneOut
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

my_params = {'n_neighbors': range(1, 16)} # 探索範囲（1以上16未満の整数）

my_search = GridSearchCV(estimator=KNeighborsRegressor(),
                         param_grid=my_params,
                         cv=LeaveOneOut(),
                         scoring='neg_mean_squared_error')
my_search.fit(X, y)

In [ ]:
tmp = my_search.cv_results_                # チューニングの詳細
my_scores = (-tmp['mean_test_score'])**0.5 # RMSE
my_results = pd.DataFrame(tmp['params']).assign(validation=my_scores)

In [ ]:
my_results.head()
#>    n_neighbors  validation
#> 0            1   20.089798
#> 1            2   17.577685
#> 2            3   16.348836
#> 3            4   16.198804
#> 4            5   16.073083

In [ ]:
my_results.plot(x='n_neighbors',
                style='o-',
                ylabel='RMSE')

In [ ]:
my_search.best_params_
#> {'n_neighbors': 5}

In [ ]:
(-my_search.best_score_)**0.5
#> 16.07308308943869

In [ ]:
my_model = my_search.best_estimator_
y_ = my_model.predict(X)
mean_squared_error(y_, y)**0.5
#> 13.087184571174962

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.neighbors import KNeighborsRegressor

my_data = sm.datasets.get_rdataset('cars', 'datasets').data
X, y = my_data[['speed']], my_data['dist']

def my_loocv(k):
    my_model = KNeighborsRegressor(n_neighbors=k)
    my_scores = cross_val_score(estimator=my_model, X=X, y=y,
                                cv=LeaveOneOut(),
                                scoring='neg_mean_squared_error')
    y_ = my_model.fit(X, y).predict(X)
    return pd.Series([k,
                      (-my_scores.mean())**0.5,        # RMSE（検証）
                      mean_squared_error(y_, y)**0.5], # RMSE（訓練）
                     index=['n_neighbors', 'validation', 'training'])

my_results = pd.Series(range(1, 16)).apply(my_loocv)

In [ ]:
my_results.plot(x='n_neighbors',
                style='o-',
                ylabel='RMSE')

# 8 回帰2（重回帰）




## 8.1 ブドウの生育条件とワインの価格

In [ ]:
import pandas as pd
my_url = 'http://www.liquidasset.com/winedata.html'
tmp = pd.read_table(my_url, skiprows=62, nrows=38, sep='\\s+', na_values='.')
tmp.describe()
#>              OBS         VINT    LPRICE2       WRAIN    DEGREES ...
#> count  38.000000    38.000000  27.000000   38.000000  37.000000 ...
#> mean   19.500000  1970.500000  -1.451765  605.000000  16.522973 ...
# 以下省略

In [ ]:
my_data = tmp.iloc[:, 2:].dropna()
my_data.head()
#>    LPRICE2  WRAIN  DEGREES ...
#> 0 -0.99868    600  17.1167 ...
#> 1 -0.45440    690  16.7333 ...
#> 3 -0.80796    502  17.1500 ...
#> 5 -1.50926    420  16.1333 ...
#> 6 -1.71655    582  16.4167 ...

In [ ]:
my_data.shape
#> (27, 5)

In [ ]:
my_data.to_csv('wine.csv',
               index=False)

In [ ]:
#my_data = pd.read_csv('wine.csv') # 作ったファイルを使う場合
my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)

## 8.2 重回帰分析

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, LeaveOneOut

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)
X, y = my_data.drop(columns=['LPRICE2']), my_data['LPRICE2']

my_model = LinearRegression().fit(X, y)

In [ ]:
my_model.intercept_
#> -12.145333576510417

pd.Series(my_model.coef_,
          index=X.columns)
#> WRAIN      0.001167
#> DEGREES    0.616392
#> HRAIN     -0.003861
#> TIME_SV    0.023847
#> dtype: float64

In [ ]:
my_test = [[500, 17, 120, 2]]
my_model.predict(my_test)
#> array([-1.49884253])

In [ ]:
y_ = my_model.predict(X)

mean_squared_error(y_, y)**0.5
#> 0.2586166620130621 # RMSE（訓練）

my_model.score(X, y)
#> 0.8275277990052154 # 決定係数1

np.corrcoef(y, y_)[0, 1]**2
#> 0.8275277990052158 # 決定係数6

In [ ]:
my_scores = cross_val_score(my_model, X, y,
                            cv=LeaveOneOut(),
                            scoring='neg_mean_squared_error')
(-my_scores.mean())**0.5
#> 0.32300426518411957 # RMSE（検証）

In [ ]:
import numpy as np
M = np.matrix(X.assign(b0=1))
b = np.linalg.pinv(M) @ y
pd.Series(b,
    index=list(X.columns) + ['b0'])
#> WRAIN       0.001167
#> DEGREES     0.616392
#> HRAIN      -0.003861
#> TIME_SV     0.023847
#> b0        -12.145334
#> dtype: float64

## 8.3 標準化

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)
X, y = my_data.drop(columns=['LPRICE2']), my_data['LPRICE2']

# StandardScalerで標準化した結果をデータフレームに戻してから描画する．
pd.DataFrame(StandardScaler().fit_transform(X), columns=X.columns
            ).boxplot(showmeans=True)

In [ ]:
my_pipeline = Pipeline([
    ('sc', StandardScaler()),
    ('lr', LinearRegression())])
my_pipeline.fit(X, y)

In [ ]:
# 線形回帰の部分だけを取り出す．
my_lr = my_pipeline.named_steps.lr
my_lr.intercept_
#> -1.4517651851851847

pd.Series(my_lr.coef_,
          index=X.columns)
#> WRAIN      0.147741
#> DEGREES    0.398724
#> HRAIN     -0.276802
#> TIME_SV    0.192979
#> dtype: float64

In [ ]:
my_test = [[500, 17, 120, 2]]
my_pipeline.predict(my_test)
#> array([-1.49884253])

## 8.4 入力変数の数とモデルの良さ

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score, LeaveOneOut

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)

n = len(my_data)
my_data2 = my_data.assign(v1=[i % 2 for i in range(n)],
                          v2=[i % 3 for i in range(n)])
my_data2.head()
#>    LPRICE2  WRAIN  DEGREES  HRAIN  TIME_SV  v1  v2
#> 0 -0.99868    600  17.1167    160       31   0   0
#> 1 -0.45440    690  16.7333     80       30   1   1
#> 2 -0.80796    502  17.1500    130       28   0   2
#> 3 -1.50926    420  16.1333    110       26   1   0
#> 4 -1.71655    582  16.4167    187       25   0   1

In [ ]:
X, y = my_data2.drop(columns=['LPRICE2']), my_data2['LPRICE2']
my_model2 = LinearRegression().fit(X, y)

y_ = my_model2.predict(X)
mean_squared_error(y_, y)**0.5
#> 0.2562120047505748 # RMSE（訓練）

my_scores = cross_val_score(my_model2, X, y,
                            cv=LeaveOneOut(),
                            scoring='neg_mean_squared_error')
(-my_scores.mean())**0.5
#> 0.3569918035928941 # RMSE（検証）

## 8.5 変数選択

In [ ]:
import pandas as pd
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV, LeaveOneOut
from sklearn.pipeline import Pipeline

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)

n = len(my_data)
my_data2 = my_data.assign(v1=[i % 2 for i in range(n)],
                          v2=[i % 3 for i in range(n)])
X, y = my_data2.drop(columns=['LPRICE2']), my_data2['LPRICE2']

In [ ]:
my_sfs = SequentialFeatureSelector(
    estimator=LinearRegression(),
    direction='forward', # 変数増加法
    cv=LeaveOneOut(),
    scoring='neg_mean_squared_error')

my_pipeline = Pipeline([         # 変数選択の後で再訓練を行うようにする．
    ('sfs', my_sfs),             # 変数選択
    ('lr', LinearRegression())]) # 回帰分析

my_params = {'sfs__n_features_to_select': range(1, 6)} # 選択する変数の上限
my_search = GridSearchCV(estimator=my_pipeline,
                         param_grid=my_params,
                         cv=LeaveOneOut(),
                         scoring='neg_mean_squared_error',
                         n_jobs=-1).fit(X, y)
my_model = my_search.best_estimator_ # 最良のパラメータで再訓練したモデル
my_search.best_estimator_.named_steps.sfs.get_support()
#> array([ True,  True,  True,  True, False, False])

## 8.6 補足：正則化

In [ ]:
import numpy as np
import pandas as pd
import warnings
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import ElasticNet, enet_path
from sklearn.model_selection import GridSearchCV, LeaveOneOut
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from scipy.stats import zscore
warnings.simplefilter('ignore', ConvergenceWarning) # これ以降，警告を表示しない．

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)
X, y = my_data.drop(columns=['LPRICE2']), my_data['LPRICE2']

In [ ]:
A = 2
B = 0.1

my_pipeline = Pipeline([
    ('sc', StandardScaler()),
    ('enet', ElasticNet(
        alpha=A,
        l1_ratio=B))])
my_pipeline.fit(X, y)

In [ ]:
my_enet = my_pipeline.named_steps.enet
my_enet.intercept_
#> -1.4517651851851852

pd.Series(my_enet.coef_,
          index=X.columns)
#> WRAIN      0.000000
#> DEGREES    0.074101
#> HRAIN     -0.041159
#> TIME_SV    0.024027
#> dtype: float64

In [ ]:
my_test = pd.DataFrame(
    [[500, 17, 120, 2]])
my_pipeline.predict(my_test)
#> array([-1.41981616])

In [ ]:
As = np.e**np.arange(2, -5.5, -0.1)
B = 0.1

_, my_path, _ = enet_path(
    zscore(X), zscore(y),
    alphas=As,
    l1_ratio=B)

pd.DataFrame(
    my_path.T,
    columns=X.columns,
    index=np.log(As)
).plot(
    xlabel='log A ( = log alpha)',
    ylabel='Coefficients')

In [ ]:
As = np.linspace(0, 0.1, 21)
Bs = np.linspace(0, 0.1,  6)

my_pipeline = Pipeline([('sc', StandardScaler()),
                        ('enet', ElasticNet())])
my_search = GridSearchCV(
    estimator=my_pipeline,
    param_grid={'enet__alpha': As, 'enet__l1_ratio': Bs},
    cv=LeaveOneOut(),
    scoring='neg_mean_squared_error',
    n_jobs=-1).fit(X, y)
my_model = my_search.best_estimator_ # 最良モデル

my_search.best_params_               # 最良パラメータ
#> {'enet__alpha': 0.075, 'enet__l1_ratio': 0.0}

In [ ]:
tmp = my_search.cv_results_                # チューニングの詳細
my_scores = (-tmp['mean_test_score'])**0.5 # RMSE

my_results = pd.DataFrame(tmp['params']).assign(RMSE=my_scores).pivot(
    index='enet__alpha',
    columns='enet__l1_ratio',
    values='RMSE')

my_results.plot(style='o-', xlabel='A ( = alpha)', ylabel='RMSE').legend(
    title='B ( = l1_ratio)')

In [ ]:
(-my_search.best_score_)**0.5
#> 0.31945619679509646

## 8.7 ニューラルネットワーク

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(-6, 6, 100)
y = 1 / (1 + np.exp(-x))
plt.plot(x, y)

In [ ]:
import pandas as pd
import warnings
from sklearn.exceptions import ConvergenceWarning
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import cross_val_score, GridSearchCV, LeaveOneOut
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)
X, y = my_data.drop(columns=['LPRICE2']), my_data['LPRICE2']

In [ ]:
warnings.simplefilter("ignore", ConvergenceWarning)  # これ以降，警告を表示しない．
my_pipeline = Pipeline([('sc', StandardScaler()),    # 標準化
                        ('mlp', MLPRegressor())])    # ニューラルネットワーク
my_pipeline.fit(X, y)                                # 訓練

my_scores = cross_val_score(my_pipeline, X, y, cv=LeaveOneOut(),
                            scoring='neg_mean_squared_error')
warnings.simplefilter("default", ConvergenceWarning) # これ以降，警告を表示する．

In [ ]:
(-my_scores.mean())**0.5
#> 0.41735891601426384

In [ ]:
my_pipeline = Pipeline([
    ('sc', StandardScaler()),
    ('mlp', MLPRegressor(tol=1e-5,         # 改善したと見なす基準
                         max_iter=5000))]) # 改善しなくなるまでの反復数
my_layers = (1, 3, 5,                                         # 隠れ層1層の場合
             (1, 1), (3, 1), (5, 1), (1, 2), (3, 2), (5, 2))  # 隠れ層2層の場合
my_params = {'mlp__hidden_layer_sizes': my_layers}
my_search = GridSearchCV(estimator=my_pipeline,
                         param_grid=my_params,
                         cv=LeaveOneOut(),
                         scoring='neg_mean_squared_error',
                         n_jobs=-1).fit(X, y)
my_model = my_search.best_estimator_ # 最良モデル

my_search.best_params_               # 最良パラメータ
#> {'mlp__hidden_layer_sizes': 5}

In [ ]:
(-my_search.best_score_)**0.5
#> 0.3759690731968538

# 9 分類1（多値分類）




## 9.1 アヤメのデータ

In [ ]:
import statsmodels.api as sm
my_data = sm.datasets.get_rdataset('iris', 'datasets').data
my_data.head()
#>    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
#> 0           5.1          3.5           1.4          0.2  setosa
#> 1           4.9          3.0           1.4          0.2  setosa
#> 2           4.7          3.2           1.3          0.2  setosa
#> 3           4.6          3.1           1.5          0.2  setosa
#> 4           5.0          3.6           1.4          0.2  setosa

In [ ]:
my_data.describe()
#>        Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
#> count    150.000000   150.000000    150.000000   150.000000
#> mean       5.843333     3.057333      3.758000     1.199333
# 以下省略

## 9.2 木による分類

In [ ]:
import graphviz
import pandas as pd
import statsmodels.api as sm
from sklearn import tree

my_data = sm.datasets.get_rdataset('iris', 'datasets').data
X, y = my_data.iloc[:, 0:4], my_data.Species

my_model = tree.DecisionTreeClassifier(max_depth=2, random_state=0)
my_model.fit(X, y)

In [ ]:
my_dot = tree.export_graphviz(
    decision_tree=my_model,
    out_file=None,                 # ファイルに出力しない．
    feature_names=X.columns,       # 変数名
    class_names=my_model.classes_, # カテゴリ名
    filled=True)                   # 色を塗る．
graphviz.Source(my_dot)

In [ ]:
my_test = pd.DataFrame([[5.0, 3.5, 1.5, 0.5],
                        [6.5, 3.0, 5.0, 2.0]])
my_model.predict(my_test)
#> array(['setosa', 'virginica'], dtype=object)

In [ ]:
pd.DataFrame(
    my_model.predict_proba(my_test),
    columns=my_model.classes_)
#>    setosa  versicolor  virginica
#> 0     1.0    0.000000   0.000000
#> 1     0.0    0.021739   0.978261

## 9.3 正解率

In [ ]:
import graphviz
import pandas as pd
import statsmodels.api as sm
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score, GridSearchCV, LeaveOneOut

my_data = sm.datasets.get_rdataset('iris', 'datasets').data
X, y = my_data.iloc[:, 0:4], my_data.Species

my_model = tree.DecisionTreeClassifier(max_depth=2, random_state=0).fit(X, y)
y_ = my_model.predict(X)
confusion_matrix(y_true=y, y_pred=y_)
#> array([[50,  0,  0],
#>        [ 0, 49,  1],
#>        [ 0,  5, 45]])

In [ ]:
my_model.score(X, y)
# あるいは
y_ = my_model.predict(X)
(y_ == y).mean()

#> 0.96

In [ ]:
cross_val_score(my_model, X, y, cv=LeaveOneOut()).mean()
#> 0.9533333333333334

In [ ]:
my_search = GridSearchCV(estimator=tree.DecisionTreeClassifier(random_state=0),
                         param_grid={'max_depth': range(1, 11)},
                         cv=LeaveOneOut(),
                         n_jobs=-1).fit(X, y)
my_search.best_params_, my_search.best_score_
#> ({'max_depth': 2}, 0.9533333333333334)

In [ ]:
my_params = {
    'max_depth': range(2, 6),
    'min_samples_split': [2, 20],
    'min_samples_leaf': range(1, 8)}

my_search = GridSearchCV(
    estimator=tree.DecisionTreeClassifier(min_impurity_decrease=0.01,
                                          random_state=0),
    param_grid=my_params,
    cv=LeaveOneOut(),
    n_jobs=-1).fit(X, y)
my_search.best_params_, my_search.best_score_
#> ({'max_depth': 3, 'min_samples_leaf': 5, 'min_samples_split': 2},
#>  0.9733333333333334)

tmp = my_search.cv_results_
my_results = pd.DataFrame(tmp['params']).assign(
    Accuracy=tmp['mean_test_score'])
# 正解率（検証）の最大値
my_results[my_results.Accuracy == my_results.Accuracy.max()]
#>     max_depth  min_samples_leaf  min_samples_split  Accuracy
#> 22          3                 5                  2  0.973333
#> 23          3                 5                 20  0.973333
#> 36          4                 5                  2  0.973333
#> 37          4                 5                 20  0.973333
#> 50          5                 5                  2  0.973333
#> 51          5                 5                 20  0.973333

In [ ]:
my_model = my_search.best_estimator_
my_dot = tree.export_graphviz(
    decision_tree=my_model,
    out_file=None,
    feature_names=X.columns,
    class_names=my_model.classes_,
    filled=True)
graphviz.Source(my_dot)

## 9.4 複数の木を使う方法

In [ ]:
import pandas as pd
import statsmodels.api as sm
import warnings
import xgboost
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, LeaveOneOut
from sklearn.preprocessing import LabelEncoder

my_data = sm.datasets.get_rdataset('iris', 'datasets').data
X, y = my_data.iloc[:, 0:4], my_data.Species
label_encoder = LabelEncoder(); y = label_encoder.fit_transform(y)

my_search = GridSearchCV(RandomForestClassifier(),
                         param_grid={'max_features': [2, 3, 4]},
                         cv=LeaveOneOut(),
                         n_jobs=-1).fit(X, y)
my_search.best_params_
#> {'max_features': 2}

my_search.cv_results_['mean_test_score']
#> array([0.96      , 0.96      , 0.95333333])

In [ ]:
warnings.simplefilter('ignore') # これ以降，警告を表示しない．
my_search = GridSearchCV(
    xgboost.XGBClassifier(eval_metric='mlogloss'),
    param_grid={'n_estimators'    : [50, 100, 150],
                'max_depth'       : [1, 2, 3],
                'learning_rate'   : [0.3, 0.4],
                'gamma'           : [0],
                'colsample_bytree': [0.6, 0.8],
                'min_child_weight': [1],
                'subsample'       : [0.5, 0.75, 1]},
    cv=5, # 5分割交差検証
    n_jobs=1).fit(X, y) # n_jobs=-1ではない．
warnings.simplefilter('default') # これ以降，警告を表示する．

my_search.best_params_
#> {'colsample_bytree': 0.6,
#>  'gamma': 0,
#>  'learning_rate': 0.3,
#>  'max_depth': 1,
#>  'min_child_weight': 1,
#>  'n_estimators': 50,
#>  'subsample': 0.75}

my_search.best_score_
#> 0.9666666666666668

In [ ]:
my_model = RandomForestClassifier().fit(X, y)
tmp = pd.Series(my_model.feature_importances_, index=X.columns)
tmp.sort_values().plot(kind='barh')

## 9.5 欠損のあるデータでの学習

In [ ]:
import numpy as np
import statsmodels.api as sm
import warnings
import xgboost
from sklearn import tree
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.pipeline import Pipeline

my_data = sm.datasets.get_rdataset('iris', 'datasets').data

n = len(my_data)
my_data['Petal.Length'] = [np.nan if i % 10 == 0 else
                           my_data['Petal.Length'][i] for i in range(n)]
my_data['Petal.Width']  = [np.nan if i % 10 == 1 else
                           my_data['Petal.Width'][i]  for i in range(n)]

my_data.describe() # countの値が135の変数に，150-135=15個の欠損がある．
#>        Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
#> count    150.000000   150.000000    135.000000   135.000000
#> mean       5.843333     3.057333      3.751852     1.197037
# 以下省略

X, y = my_data.iloc[:, 0:4], my_data.Species

In [ ]:
my_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')), # 欠損を中央値で埋める．
    ('tree', tree.DecisionTreeClassifier(random_state=0))])
my_scores = cross_val_score(my_pipeline, X, y, cv=LeaveOneOut(), n_jobs=-1)
my_scores.mean()
#> 0.9333333333333333

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

warnings.simplefilter('ignore')  # これ以降，警告を表示しない．
my_scores = cross_val_score(
    xgboost.XGBClassifier(eval_metric='mlogloss'), X, y, cv=5)
warnings.simplefilter('default') # これ以降，警告を表示する．

my_scores.mean()
#> 0.9666666666666668

## 9.6 他の分類手法

In [ ]:
import statsmodels.api as sm
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.neighbors import KNeighborsClassifier

my_data = sm.datasets.get_rdataset('iris', 'datasets').data
X, y = my_data.iloc[:, 0:4], my_data.Species

my_scores = cross_val_score(KNeighborsClassifier(), X, y, cv=LeaveOneOut())
my_scores.mean()
#> 0.9666666666666667

In [ ]:
import statsmodels.api as sm
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

my_data = sm.datasets.get_rdataset('iris', 'datasets').data
X, y = my_data.iloc[:, 0:4], my_data.Species

my_pipeline = Pipeline([('sc',  StandardScaler()),              # 標準化
                        ('mlp', MLPClassifier(max_iter=1000))]) # ニューラルネットワーク
my_scores = cross_val_score(my_pipeline, X, y, cv=LeaveOneOut(), n_jobs=-1)
my_scores.mean()
#> 0.9533333333333334

# 10 分類2（2値分類）




## 10.1 2値分類の性能指標

In [ ]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

y       = np.array([  0,   1,   1,   0,   1,   0,    1,   0,   0,   1])
y_score = np.array([0.7, 0.8, 0.3, 0.4, 0.9, 0.6, 0.99, 0.1, 0.2, 0.5])

In [ ]:
y_ = np.array([1 if 0.5 <= p else 0 for p in y_score])
y_
#> array([1, 1, 0, 0, 1, 1, 1, 0, 0, 1])

In [ ]:
confusion_matrix(y_true=y, y_pred=y_)
#> array([[3, 2],
#>        [1, 4]])

print(classification_report(y_true=y, y_pred=y_))
#>               precision    recall  f1-score   support
#>
#>            0       0.75      0.60      0.67         5
#>            1       0.67      0.80      0.73         5
#>
#>     accuracy                           0.70        10
#>    macro avg       0.71      0.70      0.70        10
#> weighted avg       0.71      0.70      0.70        10

## 10.2 トレードオフ

In [ ]:
import numpy as np
from sklearn.metrics import (roc_curve, RocCurveDisplay,
    precision_recall_curve, PrecisionRecallDisplay, auc)

y       = np.array([  0,   1,   1,   0,   1,   0,    1,   0,   0,   1])
y_score = np.array([0.7, 0.8, 0.3, 0.4, 0.9, 0.6, 0.99, 0.1, 0.2, 0.5])
y_      = np.array([1 if 0.5 <= p else 0 for p in y_score])

[sum((y == 0) & (y_ == 1)) / sum(y == 0), # FPR
 sum((y == 1) & (y_ == 1)) / sum(y == 1)] # TPR
#> [0.4, 0.8]

In [ ]:
my_fpr, my_tpr, _ = roc_curve(y_true=y,
                              y_score=y_score,
                              pos_label=1) # 1が陽性である．
RocCurveDisplay(fpr=my_fpr, tpr=my_tpr).plot()

In [ ]:
auc(x=my_fpr, y=my_tpr)
#> 0.8

In [ ]:
[sum((y == 1) & (y_ == 1)) / sum(y  == 1), # Recall == TPR
 sum((y == 1) & (y_ == 1)) / sum(y_ == 1)] # Precision
#> [0.8, 0.6666666666666666]

In [ ]:
my_precision, my_recall, _ = precision_recall_curve(y_true=y,
                                                    probas_pred=y_score,
                                                    pos_label=1)
PrecisionRecallDisplay(precision=my_precision, recall=my_recall).plot()

In [ ]:
auc(x=my_recall, y=my_precision)
#> 0.8463095238095237

## 10.3 タイタニック

In [ ]:
import graphviz
import pandas as pd
from sklearn import tree
from sklearn.metrics import roc_curve, RocCurveDisplay, auc
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/titanic.csv')
my_data = pd.read_csv(my_url)

In [ ]:
my_data.head()
#>   Class   Sex    Age Survived
#> 0   1st  Male  Child      Yes
#> 1   1st  Male  Child      Yes
#> 2   1st  Male  Child      Yes
#> 3   1st  Male  Child      Yes
#> 4   1st  Male  Child      Yes

In [ ]:
X, y = my_data.iloc[:, 0:3], my_data.Survived

my_pipeline = Pipeline([
    ('ohe', OneHotEncoder(drop='first')),
    ('tree', tree.DecisionTreeClassifier(max_depth=2, random_state=0,
                                         min_impurity_decrease=0.01))])
my_pipeline.fit(X, y)

In [ ]:
my_enc  = my_pipeline.named_steps['ohe']  # パイプラインからエンコーダを取り出す．
my_tree = my_pipeline.named_steps['tree'] # パイプラインから木を取り出す．

my_dot = tree.export_graphviz(
    decision_tree=my_tree,
    out_file=None,
    feature_names=my_enc.get_feature_names() \
    if hasattr(my_enc, 'get_feature_names') else my_enc.get_feature_names_out(),
    class_names=my_pipeline.classes_,
    filled=True)
graphviz.Source(my_dot)

In [ ]:
my_scores = cross_val_score(
    my_pipeline, X, y,
    cv=LeaveOneOut(),
    n_jobs=-1)
my_scores.mean()
#> 0.7832803271240345

In [ ]:
tmp = pd.DataFrame(
    my_pipeline.predict_proba(X),
    columns=my_pipeline.classes_)
y_score = tmp.Yes

my_fpr, my_tpr, _ = roc_curve(y_true=y,
                              y_score=y_score,
                              pos_label='Yes')
my_auc = auc(x=my_fpr, y=my_tpr)
my_auc
#> 0.7114886868858494

RocCurveDisplay(fpr=my_fpr, tpr=my_tpr, roc_auc=my_auc).plot()

## 10.4 ロジスティック回帰

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(-6, 6, 0.1)
y = 1 / (1 + np.exp(-x))
plt.plot(x, y)

In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, LeaveOneOut
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/titanic.csv')
my_data = pd.read_csv(my_url)

X, y = my_data.iloc[:, 0:3], my_data.Survived

my_pipeline = Pipeline([('ohe', OneHotEncoder(drop='first')),
                        ('lr', LogisticRegression(penalty='none'))])
my_pipeline.fit(X, y)

In [ ]:
my_ohe = my_pipeline.named_steps.ohe
my_lr  = my_pipeline.named_steps.lr

my_lr.intercept_[0]
#> 2.043878162056783

tmp = my_ohe.get_feature_names() \
if hasattr(my_ohe, 'get_feature_names') \
else my_ohe.get_feature_names_out()
pd.Series(my_lr.coef_[0],
          index=tmp)
#> x0_2nd     -1.018069
#> x0_3rd     -1.777746
#> x0_Crew    -0.857708
#> x1_Male    -2.420090
#> x2_Child    1.061531
#> dtype: float64

In [ ]:
my_scores = cross_val_score(
    my_pipeline, X, y,
    cv=LeaveOneOut(),
    n_jobs=-1)
my_scores.mean()
#> 0.7782825988187188

# 11 深層学習とAutoML




## 11.1 Kerasによる回帰

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from keras import activations, callbacks, layers, models
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle

my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
tmp = pd.read_csv(my_url)

In [ ]:
my_data = shuffle(tmp)

In [ ]:
my_scaler = StandardScaler()
X = my_scaler.fit_transform(
    my_data.drop(columns=['LPRICE2']))
y = my_data['LPRICE2']

In [ ]:
x = np.linspace(-3, 3, 100)
plt.plot(x, activations.relu(x))
plt.xlabel('x')
plt.ylabel('ReLU(x)')

In [ ]:
my_model = models.Sequential()
my_model.add(layers.Dense(units=3, activation='relu', input_shape=[4]))
my_model.add(layers.Dense(units=1))

my_model.summary() # ネットワークの概要
#> Model: "sequential"
#> _________________________________________________________________
#> Layer (type)                 Output Shape              Param #
#> =================================================================
#> dense (Dense)                (None, 3)                 15
#> _________________________________________________________________
#> dense_1 (Dense)              (None, 1)                 4
#> =================================================================
#> Total params: 19
#> Trainable params: 19
#> Non-trainable params: 0

In [ ]:
my_model.compile(
    loss='mse',
    optimizer='rmsprop')

In [ ]:
my_cb = callbacks.EarlyStopping(
    patience=20,
    restore_best_weights=True)

In [ ]:
my_history = my_model.fit(
    x=X,
    y=y,
    validation_split=0.25,
    batch_size=10,
    epochs=500,
    callbacks=[my_cb],
    verbose=0)

In [ ]:
tmp = pd.DataFrame(my_history.history)
tmp.plot(xlabel='epoch')

In [ ]:
tmp.iloc[-1, ]
#> loss        0.192743
#> val_loss    0.342249
#> Name: 499, dtype: float64

In [ ]:
y_ = my_model.predict(X)
((y_.ravel() - y)**2).mean()
#> 0.23050613964540986

## 11.2 Kerasによる分類

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from keras import callbacks, layers, losses, models
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.utils import shuffle

tmp = sm.datasets.get_rdataset('iris', 'datasets').data
my_data = shuffle(tmp)

In [ ]:
my_scaler = StandardScaler()
X = my_scaler.fit_transform(
    my_data.drop(columns=['Species']))
my_enc = LabelEncoder()
y = my_enc.fit_transform(
    my_data['Species'])

In [ ]:
my_model = models.Sequential()
my_model.add(layers.Dense(units=3, activation='relu', input_shape=[4]))
my_model.add(layers.Dense(units=3, activation='softmax'))

In [ ]:
my_model.compile(loss='sparse_categorical_crossentropy',
                 optimizer='rmsprop',
                 metrics=['accuracy'])

In [ ]:
my_cb = callbacks.EarlyStopping(
    patience=20,
    restore_best_weights=True)

my_history = my_model.fit(
    x=X,
    y=y,
    validation_split=0.25,
    batch_size=10,
    epochs=500,
    callbacks=[my_cb],
    verbose=0)

tmp = pd.DataFrame(my_history.history)
tmp.plot(xlabel='epoch')

In [ ]:
tmp.iloc[-1, ]
#> loss            0.067497
#> accuracy        0.973214
#> val_loss        0.143529
#> val_accuracy    0.921053

In [ ]:
tmp = my_model.predict(X)
y_ = np.argmax(tmp, axis=-1)
(y_ == y).mean()
#> 0.96

In [ ]:
-np.log([0.8, 0.7, 0.3, 0.8]).mean()
#> 0.5017337127232719

-np.log([0.7, 0.6, 0.2, 0.7]).mean()
#> 0.708403356019389

In [ ]:
y = [2, 1, 0, 1]
y_1 = [[0.1, 0.1, 0.8],
       [0.1, 0.7, 0.2],
       [0.3, 0.4, 0.3],
       [0.1, 0.8, 0.1]]
y_2 = [[0.1, 0.2, 0.7],
       [0.2, 0.6, 0.2],
       [0.2, 0.5, 0.3],
       [0.2, 0.7, 0.1]]

In [ ]:
[losses.sparse_categorical_crossentropy(y_true=y, y_pred=y_1).numpy().mean(),
 losses.sparse_categorical_crossentropy(y_true=y, y_pred=y_2).numpy().mean()]
#> [0.5017337, 0.70840335]

## 11.3 MNIST：手書き数字の分類

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from random import sample
from keras import callbacks, layers, models
from sklearn.metrics import confusion_matrix

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [ ]:
x_train.shape
#> (60000, 28, 28)

In [ ]:
np.set_printoptions(linewidth=170)
x_train[4, :, :]

In [ ]:
plt.matshow(x_train[4, :, :])

In [ ]:
y_train
#> array([5, 0, 4, ..., 5, 6, 8],
#>       dtype=uint8)

In [ ]:
x_train.min(), x_train.max()
#> (0, 255)

In [ ]:
x_train = x_train / 255
x_test  = x_test  / 255

In [ ]:
my_index = sample(range(60000), 6000)
x_train = x_train[my_index, :, :]
y_train = y_train[my_index]

In [ ]:
my_model = models.Sequential()
my_model.add(layers.Flatten(input_shape=[28, 28]))
my_model.add(layers.Dense(units=256, activation="relu"))
my_model.add(layers.Dense(units=10, activation="softmax"))

my_model.summary()
#> Model: "sequential"
#> _________________________________________________________________
#> Layer (type)                 Output Shape              Param #
#> =================================================================
#> flatten (Flatten)            (None, 784)               0
#> _________________________________________________________________
#> dense (Dense)                (None, 256)               200960
#> _________________________________________________________________
#> dense_1 (Dense)              (None, 10)                2570
#> =================================================================
#> Total params: 203,530
#> Trainable params: 203,530
#> Non-trainable params: 0
#> _________________________________________________________________

my_model.compile(loss='sparse_categorical_crossentropy',
                 optimizer='rmsprop',
                 metrics=['accuracy'])

my_cb = callbacks.EarlyStopping(patience=5, restore_best_weights=True)

In [ ]:
my_history = my_model.fit(
    x=x_train,
    y=y_train,
    validation_split=0.2,
    batch_size=128,
    epochs=20,
    callbacks=[my_cb],
    verbose=0)

tmp = pd.DataFrame(my_history.history)
tmp.plot(xlabel='epoch', style='o-')

In [ ]:
tmp = my_model.predict(x_test)
y_ = np.argmax(tmp, axis=-1)
confusion_matrix(y_true=y_test,
                 y_pred=y_)

In [ ]:
#> [[ 962    0    2    1    1    2    7    1    2    2]
#>  [   0 1123    4    0    0    1    3    0    4    0]
#>  [  11    4  954   11    6    2    7    9   26    2]
#>  [   3    0   20  930    2   12    2   11   21    9]
#>  [   1    1    7    0  927    1   11    1    5   28]
#>  [  10    1    3   16    4  812   11    7   24    4]
#>  [   9    3    4    0    9   10  919    0    4    0]
#>  [   3    6   17    4   11    0    0  965    2   20]
#>  [   8    4    6   12    6    9    9    7  901   12]
#>  [   9    8    0    8   31    4    1   14    7  927]]

In [ ]:
(y_ == y_test).mean()
#> 0.942

In [ ]:
my_model.evaluate(x=x_test, y=y_test)
#> [0.20125965774059296,
#>  0.9419999718666077]

In [ ]:
x_train2d = x_train.reshape(-1, 28, 28, 1)
x_test2d = x_test.reshape(-1, 28, 28, 1)

In [ ]:
my_model = models.Sequential()
my_model.add(layers.Conv2D(filters=32, kernel_size=3, # 畳み込み層
                           activation='relu',
                           input_shape=[28, 28, 1]))
my_model.add(layers.MaxPooling2D(pool_size=2))        # プーリング層
my_model.add(layers.Flatten())
my_model.add(layers.Dense(128, activation='relu'))
my_model.add(layers.Dense(10, activation='softmax'))

my_model.summary()
#> Model: "sequential"
#> _________________________________________________________________
#> Layer (type)                 Output Shape              Param #
#> =================================================================
#> conv2d (Conv2D)              (None, 26, 26, 32)        320
#> _________________________________________________________________
#> max_pooling2d (MaxPooling2D) (None, 13, 13, 32)        0
#> _________________________________________________________________
#> flatten (Flatten)            (None, 5408)              0
#> _________________________________________________________________
#> dense (Dense)                (None, 128)               692352
#> _________________________________________________________________
#> dense_1 (Dense)              (None, 10)                1290
#> =================================================================
#> Total params: 693,962
#> Trainable params: 693,962
#> Non-trainable params: 0
#> _________________________________________________________________

my_model.compile(loss='sparse_categorical_crossentropy',
                 optimizer='rmsprop',
                 metrics=['accuracy'])

from keras.callbacks import EarlyStopping
my_cb = EarlyStopping(patience=5,
                      restore_best_weights=True)

In [ ]:
my_history = my_model.fit(
    x=x_train2d,
    y=y_train,
    validation_split=0.2,
    batch_size=128,
    epochs=20,
    callbacks=my_cb,
    verbose=0)

tmp = pd.DataFrame(my_history.history)
tmp.plot(xlabel='epoch', style='o-')

In [ ]:
my_model.evaluate(x=x_test2d, y=y_test)
#> [0.1359061449766159,
#>  0.9581000208854675]

In [ ]:
my_model = models.Sequential()
my_model.add(layers.Conv2D(filters=20, kernel_size=5, activation='relu',
                           input_shape=(28, 28, 1)))
my_model.add(layers.MaxPooling2D(pool_size=2, strides=2))
my_model.add(layers.Conv2D(filters=20, kernel_size=5, activation='relu'))
my_model.add(layers.MaxPooling2D(pool_size=2, strides=2))
my_model.add(layers.Dropout(rate=0.25))
my_model.add(layers.Flatten())
my_model.add(layers.Dense(500, activation='relu'))
my_model.add(layers.Dropout(rate=0.5))
my_model.add(layers.Dense(10, activation='softmax'))

my_model.compile(loss='sparse_categorical_crossentropy',
                 optimizer='rmsprop',
                 metrics=['accuracy'])

my_cb = callbacks.EarlyStopping(patience=5,
                                restore_best_weights=True)

In [ ]:
my_history = my_model.fit(
    x=x_train2d,
    y=y_train,
    validation_split=0.2,
    batch_size=128,
    epochs=20,
    callbacks=my_cb,
    verbose=0)

tmp = pd.DataFrame(my_history.history)
tmp.plot(xlabel='epoch', style='o-')

In [ ]:
my_model.evaluate(x=x_test2d, y=y_test)
#> [0.06491111218929291,
#>  0.9797000288963318]

In [ ]:
y_prob = my_model.predict(x_test2d)                    # カテゴリに属する確率

tmp = pd.DataFrame({
    'y_prob': np.max(y_prob, axis=1),                  # 確率の最大値
    'y_': np.argmax(y_prob, axis=1),                   # 予測カテゴリ
    'y': y_test,                                       # 正解
    'id': range(len(y_test))})                         # 番号

tmp = tmp[tmp.y_ != tmp.y]                             # 予測がはずれたものを残す
my_result = tmp.sort_values('y_prob', ascending=False) # 確率の大きい順に並び替える

In [ ]:
my_result.head()
#>         y_prob  y_  y    id
#> 2654  0.999997   1  6  2654
#> 1232  0.999988   4  9  1232
#> 3520  0.999926   4  6  3520
#> 9729  0.999881   6  5  9729
#> 2896  0.999765   0  8  2896

In [ ]:
for i in range(5):
    plt.subplot(1, 5, i + 1)
    ans = my_result['y'].iloc[i]
    id = my_result['id'].iloc[i]
    plt.title(f'{ans} ({id})')
    plt.imshow(x_test[id])
    plt.axis('off')

## 11.4 AutoML

In [ ]:
import h2o
import pandas as pd
import tensorflow as tf
from h2o.automl import H2OAutoML
from random import sample

h2o.init()
h2o.no_progress()
# h2o.cluster().shutdown() # 停止

In [ ]:
my_url = ('https://raw.githubusercontent.com/taroyabuki'
          '/fromzero/master/data/wine.csv')
my_data = pd.read_csv(my_url)
my_frame = h2o.H2OFrame(my_data) # 通常のデータフレームをH2OFrameに変換する．
# あるいは
my_frame = h2o.import_file(my_url, header=1) # データを読み込む．

In [ ]:
my_frame.head(5)
#>   LPRICE2    WRAIN    DEGREES  ...
#> ---------  -------  ---------  ...
#>  -0.99868      600    17.1167  ...
#>  -0.4544       690    16.7333  ...
#>  -0.80796      502    17.15    ...
#>  -1.50926      420    16.1333  ...
#>  -1.71655      582    16.4167  ...

# 通常のデータフレームに戻す．
h2o.as_list(my_frame).head()
# 結果は割愛（見た目は同じ）

In [ ]:
my_model = H2OAutoML(
    max_runtime_secs=60)
my_model.train(
    y='LPRICE2',
    training_frame=my_frame)

In [ ]:
my_model.leaderboard['rmse'].min()
#> 0.2704643402377778

In [ ]:
tmp = h2o.as_list(
    my_model.predict(my_frame))

pd.DataFrame({
    'y': my_data['LPRICE2'],
    'y_': tmp['predict']}
).plot('y', 'y_', kind='scatter')

In [ ]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
my_index = sample(range(60000), 6000)
x_train = x_train[my_index, :, :]
y_train = y_train[my_index]

In [ ]:
tmp = pd.DataFrame(
    x_train.reshape(-1, 28 * 28))
y = 'y'
tmp[y] = y_train
my_train = h2o.H2OFrame(tmp)
my_train[y] = my_train[y].asfactor()

tmp = pd.DataFrame(
    x_test.reshape(-1, 28 * 28))
my_test = h2o.H2OFrame(tmp)

In [ ]:
my_model = H2OAutoML(
    max_runtime_secs=120)
my_model.train(
    y=y,
    training_frame=my_train)

In [ ]:
my_model.leaderboard[
    'mean_per_class_error'].min()
#> 0.06803754348177862

In [ ]:
tmp = h2o.as_list(
    my_model.predict(my_test))
y_ = tmp.predict

(y_ == y_test).mean()
#> 0.938

# 12 時系列予測




## 12.1 日時と日時の列

In [ ]:
import pandas as pd
pd.to_datetime('2020-01-01')
#> Timestamp('2020-01-01 00:00:00')

In [ ]:
pd.date_range(start='2021-01-01', end='2023-01-01', freq='1A')
#> DatetimeIndex(['2021-12-31', '2022-12-31'],
#>               dtype='datetime64[ns]', freq='A-DEC')

pd.date_range(start='2021-01-01', end='2023-01-01', freq='1AS')
#> DatetimeIndex(['2021-01-01', '2022-01-01', '2023-01-01'],
#>               dtype='datetime64[ns]', freq='AS-JAN')

pd.date_range(start='2021-01-01', end='2021-03-01', freq='2M')
#> DatetimeIndex(['2021-01-31'], dtype='datetime64[ns]', freq='2M')

pd.date_range(start='2021-01-01', end='2021-03-01', freq='2MS')
#> DatetimeIndex(['2021-01-01', '2021-03-01'],
#>               dtype='datetime64[ns]', freq='2MS')

pd.date_range(start='2021-01-01', end='2021-01-03', freq='1D')
#> DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03'],
#>               dtype='datetime64[ns]', freq='D')

pd.date_range(start='2021-01-01 00:00:00', end='2021-01-01 03:00:00', freq='2H')
#> DatetimeIndex(['2021-01-01 00:00:00', '2021-01-01 02:00:00'],
#>               dtype='datetime64[ns]', freq='2H')

## 12.2 時系列データの予測

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from pmdarima.datasets import airpassengers
from sklearn.metrics import mean_squared_error

my_data = airpassengers.load_airpassengers()

In [ ]:
n = len(my_data) # データ数（144）
k = 108          # 訓練データ数

In [ ]:
my_ds = pd.date_range(
    start='1949/01/01',
    end='1960/12/01',
    freq='MS')
my_df = pd.DataFrame({
    'ds': my_ds,
    'x': range(n),
    'y': my_data},
    index=my_ds)
my_df.head()
#>                    ds  x      y
#> 1949-01-01 1949-01-01  0  112.0
#> 1949-02-01 1949-02-01  1  118.0
#> 1949-03-01 1949-03-01  2  132.0
#> 1949-04-01 1949-04-01  3  129.0
#> 1949-05-01 1949-05-01  4  121.0

In [ ]:
my_train = my_df[        :k]
my_test  = my_df[-(n - k): ]
y = my_test.y

In [ ]:
plt.plot(my_train.y, label='train')
plt.plot(my_test.y,  label='test')
plt.legend()

In [ ]:
from sklearn.linear_model import LinearRegression

my_lm_model = LinearRegression()
my_lm_model.fit(my_train[['x']], my_train.y)

X = my_test[['x']]
y_ = my_lm_model.predict(X)
mean_squared_error(y, y_)**0.5 # RMSE（テスト）
#> 70.63707081783771

In [ ]:
y_ = my_lm_model.predict(my_df[['x']])
tmp = pd.DataFrame(y_,
                   index=my_df.index)
plt.plot(my_train.y, label='train')
plt.plot(my_test.y,  label='test')
plt.plot(tmp, label='model')
plt.legend()

In [ ]:
import pmdarima as pm
my_arima_model = pm.auto_arima(my_train.y, m=12, trace=True)
#> （省略）
#> Best model:  ARIMA(1,1,0)(0,1,0)[12]
#> Total fit time: 0.838 seconds

In [ ]:
y_, my_ci = my_arima_model.predict(len(my_test),         # 期間はテストデータと同じ．
                                   alpha=0.05,           # 有意水準（デフォルト）
                                   return_conf_int=True) # 信頼区間を求める．
tmp = pd.DataFrame({'y': y_,
                    'Lo': my_ci[:, 0],
                    'Hi': my_ci[:, 1]},
                   index=my_test.index)
tmp.head()
#>                      y          Lo          Hi
#> 1958-01-01  345.964471  327.088699  364.840243
#> 1958-02-01  331.731920  308.036230  355.427610
#> 1958-03-01  386.787992  358.515741  415.060244
#> 1958-04-01  378.774472  346.695454  410.853490
#> 1958-05-01  385.777732  350.270765  421.284700

In [ ]:
mean_squared_error(y, y_)**0.5
#> 22.132236727738697

In [ ]:
plt.plot(my_train.y, label='train')
plt.plot(my_test.y,  label='test')
plt.plot(tmp.y,      label='model')
plt.fill_between(tmp.index,
                 tmp.Lo,
                 tmp.Hi,
                 alpha=0.25) # 不透明度
plt.legend(loc='upper left')

In [ ]:
try: from fbprophet import Prophet
except ImportError: from prophet import Prophet
my_prophet_model = Prophet(seasonality_mode='multiplicative')
my_prophet_model.fit(my_train)

In [ ]:
tmp = my_prophet_model.predict(my_test)
tmp[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].head()
#>           ds        yhat  yhat_lower  yhat_upper
#> 0 1958-01-01  359.239305  350.910898  368.464588
#> 1 1958-02-01  350.690546  341.748862  359.964881
#> 2 1958-03-01  407.188556  398.483316  415.463759
#> 3 1958-04-01  398.481739  389.244105  406.742333
#> 4 1958-05-01  402.595604  393.721421  411.331761

In [ ]:
y_ = tmp.yhat
mean_squared_error(y, y_)**0.5
#> 33.795549086036466

In [ ]:
# my_prophet_model.plot(tmp) # 予測結果のみでよい場合

fig = my_prophet_model.plot(tmp)
fig.axes[0].plot(my_train.ds, my_train.y)
fig.axes[0].plot(my_test.ds, my_test.y, color='red')

# 13 教師なし学習




## 13.1 主成分分析

In [ ]:
import numpy as np
import pandas as pd
from pca import pca
from scipy.stats import zscore

my_data = pd.DataFrame(
    {'language': [  0,  20,  20,  25,  22,  17],
     'english':  [  0,  20,  40,  20,  24,  18],
     'math':     [100,  20,   5,  30,  17,  25],
     'science':  [  0,  20,   5,  25,  16,  23],
     'society':  [  0,  20,  30,   0,  21,  17]},
    index=       ['A', 'B', 'C', 'D', 'E', 'F'])
my_model = pca(n_components=5)
my_result = my_model.fit_transform(my_data) # 主成分分析の実行

In [ ]:
my_result['PC'] # 主成分スコア
#>          PC1        PC2 ...
#> A  74.907282   7.010808 ...
#> B -13.818842  -2.753459 ...
#> C -33.714034  18.417290 ...
#> D  -1.730630 -17.876372 ...
#> E -17.837474   1.064998 ...
#> F  -7.806303  -5.863266 ...

In [ ]:
my_model.biplot(legend=False)

In [ ]:
my_result['loadings']
#>      language   english      math   science   society
#> PC1 -0.207498 -0.304360  0.887261 -0.130198 -0.245204
#> PC2 -0.279463  0.325052  0.097643 -0.702667  0.559435
#> PC3  0.306117  0.615799  0.056345 -0.338446 -0.639815
#> PC4  0.764943 -0.471697 -0.007655 -0.418045  0.132455
#> PC5 -0.447214 -0.447214 -0.447214 -0.447214 -0.447214

In [ ]:
my_result['explained_var']
#> array([0.88848331, 0.97962854, 0.99858005, 1.        , 1.        ])

In [ ]:
tmp = zscore(my_data, ddof=1) # 標準化
my_result = my_model.fit_transform(
    tmp)
my_result['PC'] # 主成分スコア
#>           PC1       PC2 ...
#> 1.0  3.673722  0.568850 ...
#> 1.0 -0.652879 -0.246926 ...
#> 1.0 -1.568294  1.742598 ...
#> 1.0 -0.250504 -1.640039 ...
#> 1.0 -0.886186  0.110493 ...
#> 1.0 -0.315858 -0.534976 ...

In [ ]:
tmp = my_data - my_data.mean()
Z  = np.matrix(tmp)                       # 標準化しない場合
#Z = np.matrix(tmp / my_data.std(ddof=1)) # √不偏分散で標準化する場合
#Z = np.matrix(tmp / my_data.std(ddof=0)) # pca(normalize=True)に合わせる場合

n = len(my_data)
S = np.cov(Z, rowvar=0, ddof=0)      # 分散共分散行列
#S = Z.T @ Z / n                     # （同じ結果）
vals, vecs = np.linalg.eig(S)        # 固有値と固有ベクトル
idx = np.argsort(-vals)              # 固有値の大きい順の番号
vals, vecs = vals[idx], vecs[:, idx] # 固有値の大きい順での並べ替え
Z @ vecs                             # 主成分スコア（結果は割愛）
vals.cumsum() / vals.sum()           # 累積寄与率
#> array([0.88848331, 0.97962854, 0.99858005, 1.        , 1.        ])

In [ ]:
U, d, V =  np.linalg.svd(Z, full_matrices=False)     # 特異値分解
W = np.diag(d)

[np.isclose(Z, U @ W @ V).all(),                     # 確認1
 np.isclose(U.T @ U, np.identity(U.shape[1])).all(), # 確認2
 np.isclose(V @ V.T, np.identity(V.shape[0])).all()] # 確認3
#> [True, True, True]

U @ W                # 主成分スコア（結果は割愛）

e = d ** 2 / n       # 分散共分散行列の固有値
e.cumsum() / e.sum() # 累積寄与率
#> array([0.88848331, 0.97962854, 0.99858005, 1.        , 1.        ])

## 13.2 クラスタ分析

In [ ]:
import pandas as pd
from scipy.cluster import hierarchy

my_data = pd.DataFrame(
    {'x': [  0, -16,  10,  10],
     'y': [  0,   0,  10, -15]},
    index=['A', 'B', 'C', 'D'])

my_result = hierarchy.linkage(
    my_data,
    metric='euclidean', # 省略可
    method='complete')

In [ ]:
hierarchy.dendrogram(my_result,
    labels=my_data.index)

In [ ]:
hierarchy.cut_tree(my_result, 3)
#> array([[0], [1], [0], [2]])

# 補足（見やすくする）
my_data.assign(cluster=
  hierarchy.cut_tree(my_result, 3))
#>     x   y  cluster
#> A   0   0        0
#> B -16   0        1
#> C  10  10        0
#> D  10 -15        2

In [ ]:
import pandas as pd
import seaborn as sns

my_data = pd.DataFrame(
    {'language': [  0,  20,  20,  25,  22,  17],
     'english':  [  0,  20,  40,  20,  24,  18],
     'math':     [100,  20,   5,  30,  17,  25],
     'science':  [  0,  20,   5,  25,  16,  23],
     'society':  [  0,  20,  30,   0,  21,  17]},
    index=       ['A', 'B', 'C', 'D', 'E', 'F'])

sns.clustermap(my_data, z_score=1) # 列ごとの標準化

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans

my_data = pd.DataFrame(
    {'x': [  0, -16,  10,  10],
     'y': [  0,   0,  10, -15]},
    index=['A', 'B', 'C', 'D'])

my_result = KMeans(
    n_clusters=3).fit(my_data)

In [ ]:
my_result.labels_
#> array([1, 0, 1, 2], dtype=int32)

# 補足（見やすくする）
my_data.assign(
  cluster=my_result.labels_)
#>     x   y  cluster
#> A   0   0        1
#> B -16   0        0
#> C  10  10        1
#> D  10 -15        2

In [ ]:
import pandas as pd
import statsmodels.api as sm
from sklearn.cluster import KMeans

iris = sm.datasets.get_rdataset('iris', 'datasets').data
my_data = iris.iloc[:, 0:4]

k = range(1, 11)
my_df = pd.DataFrame({
    'k': k,
    'inertia': [KMeans(k).fit(my_data).inertia_ for k in range(1, 11)]})
my_df.plot(x='k', style='o-', legend=False)

In [ ]:
import seaborn as sns
import statsmodels.api as sm
from pca import pca
from scipy.cluster import hierarchy
from scipy.stats import zscore
from sklearn.cluster import KMeans

iris = sm.datasets.get_rdataset('iris', 'datasets').data
my_data = zscore(iris.iloc[:, 0:4])

my_model = pca() # 主成分分析
my_result = my_model.fit_transform(my_data)['PC']
my_result['Species'] = list(iris.Species)

# 非階層的クラスタ分析の場合
my_result['cluster'] = KMeans(n_clusters=3).fit(my_data).labels_

# 階層的クラスタ分析の場合
#my_result['cluster'] = hierarchy.cut_tree(
#    hierarchy.linkage(my_data, method='complete'), 3)[:,0]

sns.scatterplot(x='PC1', y='PC2', data=my_result, legend=False,
                hue='cluster',   # 色でクラスタを表現する．
                style='Species', # 形で品種を表現する．
                palette='bright')